doc: rename example directories
lenra-io/create-or-update-pr-action pull request #7
Opened 2022-02-16 09:14 UTC by shiipou

2022-02-16 11:35 UTC, jonas-martinez requested changes

2022-02-16 11:35 UTC, jonas-martinez commented on examples/README.md
> +As you can see, we have a total of 6 Git repositories that depend on each other. In our example, repository "core-code" that will contain main code of the app that will be shared on each platform (de
```suggestion
As you can see, we have a total of 6 Git repositories that depend on each other. In our example, repository "core-code" that will contain the main code of the app that will be shared on each platform (desktop-app, mobile-app, and web-app). That core-code needs the repositories "string-lib" and "protocol-lib" to compile. And as it is quite a pain to always have to manually edit the right dependency files, this action will take care of it if it's well configured.
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/README.md
> +When you publish a new release on the repository "string-lib", this action will automatically create a Pull Request on the repository "protocol-lib" and "core-code" to update the correct files and ch
```suggestion
When you publish a new release on the repository "string-lib", this action will automatically create a Pull Request on the repository "protocol-lib" and "core-code" to update the correct files and change its own link in dependency file(s).
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/README.md
> +Now we can accept changes on the repository "core-code" to update it's version of "string-lib" and "protocol-lib".
```suggestion
Now we can accept changes on the repository "core-code" to update its version of "string-lib" and "protocol-lib".
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/README.md
> +This is be awesome to use in your projects with "sementic-release" to make releases even faster and erase error of dependency managments
```suggestion
This is awesome to use in your projects with "semantic-release" to make releases even faster and avoid errors of dependency management.
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/web-app/.github/workflows/create_or_update_pr.yml
> +          name: 'Update dependecies'
```suggestion
          name: 'Update dependencies'
```

2022-02-16 11:35 UTC, jonas-martinez commented on README.md
>            name: 'Update dependecies'
```suggestion
          name: 'Update dependencies'
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/core-code/.github/workflows/create_or_update_pr.yml
>            name: 'Update dependecies'
```suggestion
          name: 'Update dependencies'
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/desktop-app/.github/workflows/create_or_update_pr.yml
>            name: 'Update dependecies'
```suggestion
          name: 'Update dependencies'
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/mobile-app/.github/workflows/create_or_update_pr.yml
> +          name: 'Update dependecies'
```suggestion
          name: 'Update dependencies'
```

2022-02-16 11:35 UTC, jonas-martinez commented on examples/protocol-lib/.github/workflows/create_or_update_pr.yml
> +          name: 'Update dependecies'
```suggestion
          name: 'Update dependencies'
```

2022-02-16 12:30 UTC, shiipou commented
@jonas-martinez Thanks for the review, I've applied your suggestions.

2022-02-16 15:38 UTC, jonas-martinez approved these changes
Looks good to me :)

2022-02-16 15:55 UTC, merged

2022-03-15 08:08 UTC, shiipou commented
:tada: This PR is included in version 1.0.0-beta.3 :tada:

The release is available on [GitHub release](https://github.com/lenra-io/create-or-update-pr-action/releases/tag/v1.0.0-beta.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: